import './globals.css'

import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Roboto_Flex as Roboto } from 'next/font/google'

import { ThemeProvider } from '@/contexts/theme-provider'
import { AuthProvider } from '@/contexts/auth-context'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })

export const metadata: Metadata = {
  title: 'Test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="pt-BR"
      className={`${roboto.variable} font-sans`}
      suppressHydrationWarning
    >
      <AuthProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <body className="min-h-screen bg-background" suppressHydrationWarning>
            {children}
          </body>
        </ThemeProvider>
      </AuthProvider>
    </html>
  )
}
